server:
  port: 8080

spring:
  application:
    name: match-service


shot-service:
  base-url: http://shot-service:8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
